import time
print("Welcome to Mega-Alakazam's Mind-Reading Math Trick!")
input()
print("Now...I know many of you dont like maths but trust me this will be fun!\n")
time.sleep(3)
print("First things first though..Can i have a volunteer?")
input()
print("Well hello there, my name is Mega_Alakazam,may i ask what your name is?")
name = input()
print("Well hello there", name,"\n")
print("I am going to show you a mind trick,and for that i need you to pick a number between 1 and 10\n")
x = int(input("Think of a number, any number, and type it here: "))
print("Now multiply your number by 2")
input()
print("Now multiply your new number by 5")
input()
print("Now divide your current number by your original number")
input()
print("Now subtract 7 from your current number\n")
time.sleep(3)
result = (x * 2) * 5 / x - 7 
print("Mega-Alakazam waves his hands and says, 'Let me peer into the depths of your mind...\n")
print("After a dramatic pause...\n")
time.sleep(7)
print("Mega-Alakazam's mind is blown! It reads your number as", result:=result)
print("Mega-Alakazam bows with a flourish and says...\n")
time.sleep(3)
print("And remember, kids, always keep a rabbit in your hat, but a python in your code!")